### ISSUE TITLE
Google有没有获取所有内购订单的接口？

### ISSUE THREAD

**Issue by gotodoit** [Lichmaker/google-api-demo#1]
大佬，我现在想要获取Google用户内购订单的接口，但是一直没有找到。不知道你那边有没有看到过，如果看到了，麻烦告知一下。需要服务端获取。

**Comment by Lichmaker** [comment]
谷歌是不支持服务端直接获取到用户所有订单的。如果实在需要的话，客户端中可以直接拉取到，拉到之后上报回来。

**Comment by gotodoit** [comment]
好的，谢谢，主要是我们现在会出现掉单的情况，想查询下Google后台进行对比。
